jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install -g npm
      - run: git status && git diff
      - run: git checkout deploy
      - run: npm run build
      - run: git status
      - run: git add .
      - run: git commit -m "Deploy $CIRCLE_SHA1"
      - run: git push origin deploy
