jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: "Update npm"
          command: |
            npm install npm@latest
            sudo rm -rf /usr/local/lib/node_modules/npm
            sudo mv node_modules/npm /usr/local/lib/node_modules/npm
            sudo chown -R 500:500 /usr/local/lib/node_modules/npm
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      # - run: npm install -g npm
      - run: git status && git diff
      - run: git checkout deploy
      - run: npm run build
      - run: git status
      - run: git add .
      - run: git commit -m "Deploy $CIRCLE_SHA1"
      - run: git push origin deploy
