jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - add_ssh_keys
      - checkout
      - run: yarn install --frozen-lockfile
      - run:
          name: "Configure git"
          command: |
            git config --global user.email "deploybot@wizproject.ml"
            git config --global user.name "Wiz Project Deploy Bot"
      - run: npm run build
      - run:
          name: "Check for changes + deploy"
          command: |
            git status
            if [[ `git status --ignored --porcelain | grep -v node` ]]; then
              echo Changes
              git add -f public
              git commit -m "Deploy $CIRCLE_SHA1"
              git push origin deploy
            fi
