jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        name: Installing packages
        command: |
          if [[ $CIRCLE_BRANCH == *"greenkeeper"* ]]; then
            yarn install
          else
            yarn install --frozen-lockfile
          fi
      - run: npm run build
